views:
  - id:
      id: events
      type: modelList
    title: Workshops
    menuItem:
      title: All Workshops
      svgSrc: assets/icons/menu_doc.svg
      group: event-system
    layouts:
      defaultList:
        type: modelList
        fieldCombos:
          - "state"
          - |
            title
            slug
          - "starts"
          - "ends"
          - "[locationName](locationURL)"
  - id:
      id: events
      type: modelCreate
    title: Create a new workshop
    menuItem:
      title: Create Workshop
      svgSrc: assets/icons/menu_doc.svg
      group: event-system
menuGroups:
  event-system:
    title: Event System
    description: Manage events & subscriptions